{
 "title": "Juniper Telemetry Interface",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SHOW TAG VALUES FROM \"/interfaces/\" WITH KEY = \"device\""
   },
   {
    "name": "Interface",
    "query": "SHOW TAG VALUES FROM \"/interfaces/\" WITH KEY = \"/interfaces/interface/@name\" WHERE \"device\" =~ /^$Device$/"
   },
   {
    "name": "IfDescription",
    "query": "SELECT \"/interfaces/interface/state/description\" FROM /interfaces/ WHERE (\"/interfaces/interface/@name\" =~ /^$Interface$/ AND \"device\" =~ /^$Device$/)"
   },
   {
    "name": "bgp_peers",
    "query": "SHOW TAG VALUES FROM \"/network-instances/\" WITH KEY = \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\" WHERE \"device\" =~ /^$Device$/"
   },
   {
    "name": "enabled_bfd_sessions",
    "query": "SELECT \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\",\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/enable-bfd/state/enabled\" FROM /network-instances/ WHERE \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\" =~/.*/ AND \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/enable-bfd/state/enabled\" = True AND \"device\" =~ /^$Device$/ AND time > now() - 5m"
   },
   {
    "name": "transceiver",
    "query": "SELECT \"/interfaces/interface/state/transceiver\" FROM /interfaces/ WHERE \"device\" =~ /^$Device$/ AND \"/interfaces/interface/@name\" =~ /^$Interface$/"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "CPU Utilization",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "/components/component/@name::tag"
         ],
         "type": "tag"
        },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "re",
       "select": [
        [
         {
          "params": [
           "/components/component/properties/property/state/value"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " * -1 + 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/.*/"
        },
        {
         "condition": "AND",
         "key": "/components/component/properties/property/@name::tag",
         "operator": "=",
         "value": "cpu-utilization-idle"
        }
       ]
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Memory Utilization",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "/components/component/@name::tag"
         ],
         "type": "tag"
        },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "re",
       "select": [
        [
         {
          "params": [
           "/components/component/properties/property/state/value"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/.*/"
        },
        {
         "condition": "AND",
         "key": "/components/component/properties/property/@name::tag",
         "operator": "=",
         "value": "memory-utilization-buffer"
        }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "/components/component/@name::tag"
         ],
         "type": "tag"
        }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/properties/property/state/value"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/.*/"
        },
        {
         "condition": "AND",
         "key": "/components/component/properties/property/@name::tag",
         "operator": "=",
         "value": "temperature"
        }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Uptime",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "/components/component/@name::tag"
         ],
         "type": "tag"
        }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/properties/property/state/value"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=",
         "value": "Routing Engine0"
        },
        {
         "condition": "AND",
         "key": "/components/component/properties/property/@name::tag",
         "operator": "=",
         "value": "uptime"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Description",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Description",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/description"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Admin Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "admin-status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/admin-status"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Operational Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "oper-status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/oper-status"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Speed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Speed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/ethernet/state/negotiated-port-speed"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Duplex",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Duplex",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/ethernet/state/negotiated-duplex-mode"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "MTU",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 17, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "MTU",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/mtu"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "MAC Address",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "MAC",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/ethernet/state/mac-address"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Interface Bandwidth - $Interface - $IfDescription",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "alias": "RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/in-octets"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      },
      {
       "alias": "TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/out-octets"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Interface PPS - $Interface - $IfDescription",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/in-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      },
      {
       "alias": "TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/out-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Unicast PPS - $Interface - $IfDescription",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/in-unicast-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      },
      {
       "alias": "TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/out-unicast-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Broadcast PPS - $Interface - $IfDescription",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/in-broadcast-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      },
      {
       "alias": "TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/out-broadcast-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Multicast PPS - $Interface - $IfDescription",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/in-multicast-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      },
      {
       "alias": "TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/interfaces/",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/out-multicast-pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/interfaces/interface/@name::tag",
         "operator": "=~",
         "value": "/^$Interface$/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Transcievers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Type",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Type",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/transceiver/state/ethernet-pmd"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/^$transceiver$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Vendor",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Vendor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/transceiver/state/vendor"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/^$transceiver$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Connector",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Connector",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/transceiver/state/connector-type"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/^$transceiver$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Serial number",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Serial number",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/transceiver/state/serial-no"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/^$transceiver$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Output Power - $Interface",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": " dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Output power",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "/components/component/transceiver/physical-channels/channel/@index::tag"
         ],
         "type": "tag"
        }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/transceiver/physical-channels/channel/state/output-power/instant"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/^$transceiver$/"
        },
        {
         "condition": "AND",
         "key": "/components/component/transceiver/physical-channels/channel/@index::tag",
         "operator": "=~",
         "value": "/.*/"
        }
       ]
      }
     ]
    },
    {
     "title": "Input Power - $Interface",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": " dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "input power",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "/components/component/transceiver/physical-channels/channel/@index::tag"
         ],
         "type": "tag"
        }
       ],
       "measurement": "/components/",
       "select": [
        [
         {
          "params": [
           "/components/component/transceiver/physical-channels/channel/state/input-power/instant"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/components/component/@name::tag",
         "operator": "=~",
         "value": "/^$transceiver$/"
        },
        {
         "condition": "AND",
         "key": "/components/component/transceiver/physical-channels/channel/@index::tag",
         "operator": "=~",
         "value": "/.*/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BGP Session State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "BGP Session State - $bgp_peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 49 },
     "repeat": "bgp_peers",
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "session-state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/network-instances/",
       "select": [
        [
         {
          "params": [
           "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address::tag",
         "operator": "=~",
         "value": "/^$bgp_peers$/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BFD Session State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "BFD Session State - $enabled_bfd_sessions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
     "repeat": "enabled_bfd_sessions",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "session-state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/network-instances/",
       "select": [
        [
         {
          "params": [
           "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/enable-bfd/state/jnx-session-state"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$Device$/" },
        {
         "condition": "AND",
         "key": "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address::tag",
         "operator": "=~",
         "value": "/^$enabled_bfd_sessions$/"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}